name: Create a sample provenance

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
    # ${{ matrix.node-version }}
      uses: actions/setup-node@v3.1.1
      with:
        # node-version: ${{ matrix.node-version }}
        # cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: npm install
      run: npm install 
# --package-lock
    - run: npm run build
    - name: Copy and zip build files
      run: |
        mkdir prearchive
        cp -r **/*.js ./prearchive/
        cp package.json ./prearchive/
        cp package-lock.json ./prearchive/
        zip veracode-scan-target.zip ./prearchive/*
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
         name: veracode-scan-target
         path: veracode-scan-target.zip

  generate-provenance:
    needs: build
    name: Generate build provenance
    runs-on: ubuntu-latest
    steps:
      # checkout only required to run local action (defined in this repo)
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2

      - name: Generate provenance
        # use action in the root directory
        uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: artifact/veracode-scan-target.zip

      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          path: build.provenance
