name: Testing Level 3 SLSA

on:
  workflow_dispatch:
  
jobs:
  # This step builds our artifacts, uploads them to the workflow run, and
  # outputs their digest.
  build:
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    runs-on: ubuntu-latest
    steps:
      - name: Build artifacts
        run: |
          # These are some amazing artifacts.
          echo "onion, tomato, jalapeno, cilantro, lime, salt" > artifact1

      - name: Generate hashes
        shell: bash
        id: hash
        run: |
          # sha256sum generates sha256 hash for all artifacts.
          # base64 -w0 encodes to base64 and outputs on a single line.
          # sha256sum artifact1 artifact2 ... | base64 -w0
          echo "::set-output name=hashes::$(sha256sum artifact1 | base64 -w0)"

      - name: Upload artifact1
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
        with:
          name: artifact1
          path: artifact1
          if-no-files-found: error
          retention-days: 5

  # This step calls the generic workflow to generate provenance.
  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.2.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      # Upload provenance to a new release
      upload-assets: true

  # This step uploads our artifacts to the tagged GitHub release.
  release:
    needs: [build, provenance]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact1
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v2.1.0
        with:
          name: artifact1

      - name: Upload assets
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # v0.1.14
        with:
          files: |
            artifact1
            
  verify-provenance:
    needs: provenance
    runs-on: ubuntu-latest
    name: Verify Provenance
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v3.2.1
      with:
        go-version: 1.18
    - name: Verify Provenance File
      uses: actions/download-artifact@v2
    - run: |
        git clone https://github.com/slsa-framework/slsa-verifier.git
        cd slsa-verifier && git checkout v1.2.0
        ls /home/runner/work/provenance-test/provenance-test/artifact1
        go run . -artifact-path /home/runner/work/provenance-test/provenance-test/artifact1/artifact1 -provenance /home/runner/work/provenance-test/provenance-test/attestation.intoto.jsonl/attestation.intoto.jsonl -source github.com/carson-love175/provenance-test -print-provenance
        cat attestation.intoto.jsonl | jq -r '.payload' | base64 -d | jq
