name: Create simple provenance-test Thais

on:
  workflow_dispatch:


jobs:
  build:
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    runs-on: ubuntu-latest
    steps:
      - name: Build artifact
        run:  echo "onion, tomato, jalapeno, cilantro, lime, salt" > artifact1

      - name: Generate hashes
        shell: bash
        id: hash
        run: |
          echo "::set-output name=hashes::$(sha256 artifact1 | base64 -w0)"
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact1
          path: artifact1

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.2.0
    with: 
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      attestation-name: "artifact1.intoto.jsonl"
      upload-assets: true
