name: Create simple provenance-test Thais

on:
  workflow_dispatch:


jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      # traditionally you would build your code here and generate an artifact
      - name: Create artifact
        run:  echo "onion, tomato, jalapeno, cilantro, lime, salt" > salsa.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: salsa.txt

  generate-provenance:
    needs: build
    name: Generate build provenance
    runs-on: ubuntu-latest
    steps:
      # checkout only required to run local action (defined in this repo)
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2

      - name: Generate provenance
        # use action in the root directory
        uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: artifact/

      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          path: build.provenance
          
  download-artifact:
    needs: generate-provenance
    runs-on: ubuntu-latest
    name: Download Artifact
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: artifact

  verify-provenance:
    needs: download-artifact
    runs-on: ubuntu-latest
    name: Verify Provenance
    steps:
    - run: go install github.com/slsa-framework/slsa-verifier@v1.1.1
  
