name: Create Artifact and Provence from files

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Collect Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Collect test.js file
        run: |
              tree -a
              mkdir artifact
              cp tests/test.js ./artifact
              cp package-lock.js ./artifact
              cp package.js ./artifact
              zip artifact.zip ./artifact
      - name: Upload Artifact to Github
        uses: actions/upload-artifact@v2
        with:
            path: artifact.zip
            
  generate-provenance:
    needs: build
    name: Generate build provenance
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2

      - name: Generate provenance
        uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: artifact/

      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          name: provenance
          path: build.provenance
